name: Node.js Package
on:
  push:
    branches: [master]
  pull_request:

jobs:     
  changelog:
    if: ${{ github.ref == 'refs/heads/master' }} 
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm ci

      # Creates tags and updates changelog based on change changelog-config.js settings
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with: 
          github-token: ${{secrets.GITHUB_TOKEN}}
          config-file-path: ./changelog-config.js
      
      - name: Fail if tagging is skipped
        if: ${{ steps.changelog.outputs.skipped == 'true' }}
        run: exit 1