name: Node.js Package
on:
  push:
    branches: [master]
  pull_request:

jobs: 
  publish-dev:
    if: ${{ github.event_name == 'pull_request' }} 
    runs-on: ubuntu-latest
    permissions: 
      packages: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tfso'

      - name: Publish prerelease to GitHub Packages
        run: |
          npm version prerelease --preid=branch.${{github.run_number}} --no-git-tag-version
          npm publish --verbose --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  changelog:
    if: ${{ github.ref == 'refs/heads/master' }} 
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - uses: actions/checkout@v2

      # Creates tags and updates changelog based on change changelog-config.js settings
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with: 
          github-token: ${{secrets.GITHUB_TOKEN}}
          config-file-path: ./changelog-config.js
      
      - name: Fail if tagging is skipped
        if: ${{ steps.changelog.outputs.skipped == 'true' }}
        run: exit 1

  publish-prod:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: changelog
    runs-on: ubuntu-latest
    permissions: 
      packages: write
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tfso'
          
      - name: Publish to Github Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
